MKTDotNetCore.MVCChartApp/Controllers/ApexChartController.cs
using Microsoft.AspNetCore.Mvc;
using MKTDotNetCore.MVCChartApp.Models;

namespace MKTDotNetCore.MVCChartApp.Controllers
{
    public class ApexChartController : Controller
    {
        public IActionResult SimplePieChart()
        {
            SimplePieChartModel model = new SimplePieChartModel();
            model.Lables = new List<string>() { "Team A", "Team B", "Team C", "Team D", "Team E" };
            model.Series = new List<int> { 44, 55, 13, 43, 22 };
            return View(model);
        }
    }
}

MKTDotNetCore.MVCChartApp/Controllers/CanvasJsController.cs
using Microsoft.AspNetCore.Mvc;
using MKTDotNetCore.MVCChartApp.Models;

namespace MKTDotNetCore.MVCChartApp.Controllers
{
    public class CanvasJsController : Controller
    {
        private readonly ILogger<CanvasJsController> _logger;

        public CanvasJsController(ILogger<CanvasJsController> logger)
        {
            _logger = logger;
        }

        public IActionResult LineChart()
        {
            _logger.LogInformation("Starting Line Chart");
            var lst = new List<CanvasLineChartModel>()
            {
                new CanvasLineChartModel
                {
                    y=450
                },
                new CanvasLineChartModel
                {
                    y=414
                },
                new CanvasLineChartModel
                {
                    y=520
                },
                new CanvasLineChartModel
                {
                    y=460
                },
                new CanvasLineChartModel
                {
                    y=450
                },
                new CanvasLineChartModel
                {
                    y=500
                },
                new CanvasLineChartModel
                {
                    y=480
                },
                new CanvasLineChartModel
                {
                    y=480
                },
                new CanvasLineChartModel
                {
                    y=410
                },
                new CanvasLineChartModel
                {
                    y=500
                },
                new CanvasLineChartModel
                {
                    y=480
                },
                new CanvasLineChartModel
                {
                    y=510
                }
            };
            return View(lst);
        }
    }
}

MKTDotNetCore.MVCChartApp/Controllers/ChartJsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MKTDotNetCore.MVCChartApp.Controllers
{
    public class ChartJsController : Controller
    {
        public IActionResult ExampleChart()
        {
            return View();
        }

        public IActionResult InterpolationLineChart()
        {
            return View();
        }
    }
}

MKTDotNetCore.MVCChartApp/Controllers/HighChartController.cs
using Microsoft.AspNetCore.Mvc;
using MKTDotNetCore.MVCChartApp.Models;

namespace MKTDotNetCore.MVCChartApp.Controllers
{
    public class HighChartController : Controller
    {
        public IActionResult PieChart()
        {
            var lst = new List<PieChartModel>()
            {
                new PieChartModel
                {
                    name="Apple",
                    y=12.33m
                },
                new PieChartModel
                {
                    name="Orange",
                    y=10.33m
                },
                new PieChartModel
                {
                    name="Grape",
                    y=20.99m
                },
                new PieChartModel
                {
                    name="Coca-Cola",
                    y=18.99m
                }
            };
            return View(lst);
        }

        public IActionResult AreaChart()
        {
            var model = new AreaChartModel
            {
                usa = [
            1,
                    2,
                    3,
                    6,
                    5,
                    2,
                    9,
                    13,
                    50,
                    170,
                    299,
                    438,
                    841,
                    1169,
                    1703,
                    2422,
                    3692,
                    5543,
                    7345,
                    12298,
                    18638,
                    22229,
                    25540,
                    28133,
                    29463,
                    31139,
                    31175,
                    31255,
                    29561,
                    27552,
                    26008,
                    25830,
                    26516,
                    27835,
                    28537,
                    27519,
                    25914,
                    25542,
                    24418,
                    24138,
                    24104,
                    23208,
                    22886,
                    23305,
                    23459,
                    23368,
                    23317,
                    23575,
                    23205,
                    22217,
                    21392,
                    19008,
                    13708,
                    11511,
                    10979,
                    10904,
                    11011,
                    10903,
                    10732,
                    10685,
                    10577,
                    10526,
                    10457,
                    10027,
                    8570,
                    8360,
                    7853,
                    5709,
                    5273,
                    5113,
                    5066,
                    4897,
                    4881,
                    4804,
                    4717,
                    4571,
                    4018,
                    3822,
                    3785,
                    3805,
                    3750,
                    3708,
                    3708,
                    3708,
                    3708
        ],
                ussr= [
            0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    5,
                    25,
                    50,
                    120,
                    150,
                    200,
                    426,
                    660,
                    863,
                    1048,
                    1627,
                    2492,
                    3346,
                    4259,
                    5242,
                    6144,
                    7091,
                    8400,
                    9490,
                    10671,
                    11736,
                    13279,
                    14600,
                    15878,
                    17286,
                    19235,
                    22165,
                    24281,
                    26169,
                    28258,
                    30665,
                    32146,
                    33486,
                    35130,
                    36825,
                    38582,
                    40159,
                    38107,
                    36538,
                    35078,
                    32980,
                    29154,
                    26734,
                    24403,
                    21339,
                    18179,
                    15942,
                    15442,
                    14368,
                    13188,
                    12188,
                    11152,
                    10114,
                    9076,
                    8038,
                    7000,
                    6643,
                    6286,
                    5929,
                    5527,
                    5215,
                    4858,
                    4750,
                    4650,
                    4600,
                    4500,
                    4490,
                    4300,
                    4350,
                    4330,
                    4310,
                    4495,
                    4477,
                    4489,
                    4380
        ]
            };
            return View(model);
        }
    }
}

MKTDotNetCore.MVCChartApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MKTDotNetCore.MVCChartApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MKTDotNetCore.MVCChartApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MKTDotNetCore.MVCChartApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Chart
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ApexChart" asp-action="SimplePieChart">SimplePieChart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ChartJs" asp-action="ExampleChart">ExampleChart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ChartJs" asp-action="InterpolationLineChart">InterpolationLineChart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="HighChart" asp-action="PieChart">PieChart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="HighChart" asp-action="AreaChart">AreaChart</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="CanvasJs" asp-action="LineChart">CanvasLineChart</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MKTDotNetCore.MVCChartApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <script src="https://cdn.canvasjs.com/canvasjs.min.js"></script>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>